# This is a basic workflow to help you get started with Actions

name: Black Duck CI

# Controls when the workflow will run
on: [push]
# Triggers the workflow on push or pull request events but only for the master branch

jobs: 
  build:
  
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
      steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
          
      - name: Build with Maven
        run: mvn -B compile
        
        env:
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
          PROJECT: rodv-ram
          BRANCH: ${GITHUB_REF##*/}
      
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.0
        with: 
          args: --detect.project.name=$PROJECT --detect.project.version.name=$BRANCH
